### ISSUE TITLE
[updtream]runtime/CompressedOops/CompressedClassPointers.java fail on aarch64

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell17#115]
```log
java.lang.RuntimeException: 'Narrow klass base: 0x0000000000000000' missing from stdout/stderr 

        at jdk.test.lib.process.OutputAnalyzer.shouldContain(OutputAnalyzer.java:221)
        at CompressedClassPointers.smallHeapTestNoCoop(CompressedClassPointers.java:209)
        at CompressedClassPointers.main(CompressedClassPointers.java:335)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sendaoYan** [comment]
runtime/CompressedOops/CompressedClassPointers.java https://github.com/dragonwell-project/dragonwell17/issues/115 linux-aarch64

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8305765

**Comment by sendaoYan** [comment]
f45b01f8830a8d42a486374e8c3dadc845bfc59f

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/7018e5d2-1296-4343-b48f-f270805cce04)

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8305766

**Comment by sendaoYan** [comment]
jdk17社区已经合入

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/7067f7de-97b4-4ad5-b259-8421ab6a609f)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14205931

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/17005832
