### ISSUE TITLE
【上游问题】-Xcomp选项java/nio/channels/DatagramChannel/StressNativeSignal.java随机超时

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell17#44]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147439?tab=1

```log
ACTION: main -- Error. Program `/opt/java/openjdk/bin/java' timed out (timeout set to 480000ms, elapsed time including timeout handling was 480223ms).
REASON: Assumed action based on file name: run main StressNativeSignal 
TIME:   480.224 seconds
messages:
command: main StressNativeSignal
reason: Assumed action based on file name: run main StressNativeSignal 
Mode: othervm
Timeout information:
Running jstack on process 3350717
2023-02-20 15:23:40
Full thread dump OpenJDK 64-Bit Server VM (17.0.6+9 compiled mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fefc8001e30, length=15, elements={
0x00007ff05c026a60, 0x00007ff05c334b80, 0x00007ff05c335f60, 0x00007ff05c33efc0,
0x00007ff05c340370, 0x00007ff05c341780, 0x00007ff05c3431f0, 0x00007ff05c344760,
0x00007ff05c345bd0, 0x00007ff05c348f00, 0x00007ff05c3501f0, 0x00007ff05c3914f0,
0x00007fefac005a80, 0x00007fefac002d30, 0x00007fefc8000e70
}

"main" #1 prio=5 os_prio=0 cpu=90.59ms elapsed=480.20s tid=0x00007ff05c026a60 nid=0x3320c0 in Object.wait()  [0x00007ff065d61000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@17.0.6/Thread.java:1304)
	- locked <0x0000000101073db0> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@17.0.6/Thread.java:1372)
	at com.sun.javatest.regtest.agent.MainWrapper.main(MainWrapper.java:74)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.13ms elapsed=480.19s tid=0x00007ff05c334b80 nid=0x3320c7 waiting on condition  [0x00007fefe72ae000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.6/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@17.0.6/Reference.java:253)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.6/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.22ms elapsed=480.19s tid=0x00007ff05c335f60 nid=0x3320c8 in Object.wait()  [0x00007fefe71ad000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <0x0000000101002f40> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.6/ReferenceQueue.java:155)
	- locked <0x0000000101002f40> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.6/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.6/Finalizer.java:172)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.51ms elapsed=480.18s tid=0x00007ff05c33efc0 nid=0x3320c9 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.16ms elapsed=480.18s tid=0x00007ff05c340370 nid=0x3320ca runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=5.98ms elapsed=480.18s tid=0x00007ff05c341780 nid=0x3320cb runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=6054.25ms elapsed=480.18s tid=0x00007ff05c3431f0 nid=0x3320cc waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #21 daemon prio=9 os_prio=0 cpu=1231.45ms elapsed=480.18s tid=0x00007ff05c344760 nid=0x3320cd waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #28 daemon prio=9 os_prio=0 cpu=34.10ms elapsed=480.18s tid=0x00007ff05c345bd0 nid=0x3320ce runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Notification Thread" #29 daemon prio=9 os_prio=0 cpu=0.06ms elapsed=479.71s tid=0x00007ff05c348f00 nid=0x3320e5 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #30 daemon prio=8 os_prio=0 cpu=0.49ms elapsed=479.25s tid=0x00007ff05c3501f0 nid=0x332113 in Object.wait()  [0x00007fefe5a7e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.6/ReferenceQueue.java:155)
	- locked <0x000000010101cce8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@17.0.6/CleanerImpl.java:140)
	at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
	at jdk.internal.misc.InnocuousThread.run(java.base@17.0.6/InnocuousThread.java:162)

"MainThread" #32 prio=5 os_prio=0 cpu=11.07ms elapsed=477.64s tid=0x00007ff05c3914f0 nid=0x332277 in Object.wait()  [0x00007fefe597d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <no object reference available>
	at java.lang.Thread.join(java.base@17.0.6/Thread.java:1304)
	- locked <0x00000001017b3138> (a StressNativeSignal$UDPThread)
	at java.lang.Thread.join(java.base@17.0.6/Thread.java:1372)
	at StressNativeSignal.shutdown(StressNativeSignal.java:64)
	at StressNativeSignal.main(StressNativeSignal.java:58)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.6/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.6/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.6/Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)

"Thread-1" #33 prio=5 os_prio=0 cpu=55.45ms elapsed=477.45s tid=0x00007fefac005a80 nid=0x33228c runnable  [0x00007fefe55fe000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.accept(java.base@17.0.6/Native Method)
	at sun.nio.ch.NioSocketImpl.accept(java.base@17.0.6/NioSocketImpl.java:755)
	at java.net.ServerSocket.implAccept(java.base@17.0.6/ServerSocket.java:675)
	at java.net.ServerSocket.platformImplAccept(java.base@17.0.6/ServerSocket.java:641)
	at java.net.ServerSocket.implAccept(java.base@17.0.6/ServerSocket.java:617)
	at java.net.ServerSocket.implAccept(java.base@17.0.6/ServerSocket.java:574)
	at java.net.ServerSocket.accept(java.base@17.0.6/ServerSocket.java:532)
	at StressNativeSignal$ServerSocketThread.run(StressNativeSignal.java:84)

"Thread-2" #34 prio=5 os_prio=0 cpu=78.54ms elapsed=477.44s tid=0x00007fefac002d30 nid=0x33228d runnable  [0x00007fefe51fe000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.DatagramChannelImpl.receive0(java.base@17.0.6/Native Method)
	at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(java.base@17.0.6/DatagramChannelImpl.java:750)
	at sun.nio.ch.DatagramChannelImpl.receive(java.base@17.0.6/DatagramChannelImpl.java:736)
	at sun.nio.ch.DatagramChannelImpl.receive(java.base@17.0.6/DatagramChannelImpl.java:543)
	at StressNativeSignal$UDPThread.run(StressNativeSignal.java:127)

"Attach Listener" #35 daemon prio=9 os_prio=0 cpu=0.23ms elapsed=0.10s tid=0x00007fefc8000e70 nid=0x33de15 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=11.10ms elapsed=480.19s tid=0x00007ff05c330c00 nid=0x3320c6 runnable  

"GC Thread#0" os_prio=0 cpu=0.53ms elapsed=480.20s tid=0x00007ff05c068e10 nid=0x3320c1 runnable  

"G1 Main Marker" os_prio=0 cpu=0.05ms elapsed=480.20s tid=0x00007ff05c0795a0 nid=0x3320c2 runnable  

"G1 Conc#0" os_prio=0 cpu=0.05ms elapsed=480.20s tid=0x00007ff05c07a590 nid=0x3320c3 runnable  

"G1 Refine#0" os_prio=0 cpu=0.05ms elapsed=480.19s tid=0x00007ff05c2f46c0 nid=0x3320c4 runnable  

"G1 Service" os_prio=0 cpu=39.70ms elapsed=480.19s tid=0x00007ff05c2f55b0 nid=0x3320c5 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=145.44ms elapsed=479.71s tid=0x00007ff05c34efd0 nid=0x3320e6 waiting on condition  

JNI global refs: 32, weak refs: 0

--- Timeout information end.
elapsed time (seconds): 480.224
configuration:
STDOUT:
Timeout refired 480 times
STDERR:
java.lang.NullPointerException: Cannot invoke "java.nio.channels.DatagramChannel.close()" because "this.channel" is null
	at StressNativeSignal$UDPThread.terminate(StressNativeSignal.java:139)
	at StressNativeSignal.shutdown(StressNativeSignal.java:62)
	at StressNativeSignal.main(StressNativeSignal.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)
rerun:
cd /tmp/tone/run/jtreg/jt-work/test_jdk/java/nio/channels/DatagramChannel/StressNativeSignal && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/166/java/nio/channels/DatagramChannel/StressNativeSignal.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/nio/channels/DatagramChannel:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/jdk \
        -Dtest.name=java/nio/channels/DatagramChannel/StressNativeSignal.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/nio/channels/DatagramChannel/StressNativeSignal.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/nio/channels/DatagramChannel \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/nio/channels/DatagramChannel \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/166/java/nio/channels/DatagramChannel/StressNativeSignal.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/166/java/nio/channels/DatagramChannel/StressNativeSignal.d \
        -Xcomp \
        -ea \
        -esa \
        -Djava.library.path=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/test_jdk/java/nio/channels/DatagramChannel/StressNativeSignal.d/main.0.jta

TEST RESULT: Error. Program `/opt/java/openjdk/bin/java' timed out (timeout set to 480000ms, elapsed time including timeout handling was 480223ms).
```

replay command:
```bash
test=test/jdk/java/nio/channels/DatagramChannel/StressNativeSignal.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P $nproc bash -c "jtreg -Xcomp -ea -esa -timeoutFactor:2 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```
[12.log](https://github.com/alibaba/dragonwell17/files/10789073/12.log)

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk/pull/20050
